// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// set_seed
void set_seed(int seed);
RcppExport SEXP _KODAMA_set_seed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    set_seed(seed);
    return R_NilValue;
END_RCPP
}
// floyd
arma::mat floyd(arma::mat data);
RcppExport SEXP _KODAMA_floyd(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(floyd(data));
    return rcpp_result_gen;
END_RCPP
}
// transformy
arma::mat transformy(arma::ivec y);
RcppExport SEXP _KODAMA_transformy(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(transformy(y));
    return rcpp_result_gen;
END_RCPP
}
// PLSDACV_simpls
arma::ivec PLSDACV_simpls(arma::mat x, arma::ivec cl, arma::ivec constrain, int k);
RcppExport SEXP _KODAMA_PLSDACV_simpls(SEXP xSEXP, SEXP clSEXP, SEXP constrainSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type cl(clSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(PLSDACV_simpls(x, cl, constrain, k));
    return rcpp_result_gen;
END_RCPP
}
// PLSDACV_fastpls
arma::ivec PLSDACV_fastpls(arma::mat x, arma::ivec cl, arma::ivec constrain, int k);
RcppExport SEXP _KODAMA_PLSDACV_fastpls(SEXP xSEXP, SEXP clSEXP, SEXP constrainSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type cl(clSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(PLSDACV_fastpls(x, cl, constrain, k));
    return rcpp_result_gen;
END_RCPP
}
// corecpp
List corecpp(arma::mat x, arma::mat xTdata, arma::ivec clbest, const int Tcycle, int FUN, int fparpls, arma::ivec Xconstrain, NumericVector fix, bool shake, int proj);
RcppExport SEXP _KODAMA_corecpp(SEXP xSEXP, SEXP xTdataSEXP, SEXP clbestSEXP, SEXP TcycleSEXP, SEXP FUNSEXP, SEXP fparplsSEXP, SEXP XconstrainSEXP, SEXP fixSEXP, SEXP shakeSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xTdata(xTdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type clbest(clbestSEXP);
    Rcpp::traits::input_parameter< const int >::type Tcycle(TcycleSEXP);
    Rcpp::traits::input_parameter< int >::type FUN(FUNSEXP);
    Rcpp::traits::input_parameter< int >::type fparpls(fparplsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type Xconstrain(XconstrainSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fix(fixSEXP);
    Rcpp::traits::input_parameter< bool >::type shake(shakeSEXP);
    Rcpp::traits::input_parameter< int >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(corecpp(x, xTdata, clbest, Tcycle, FUN, fparpls, Xconstrain, fix, shake, proj));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP KODAMA_irlba_pca_dense(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_KODAMA_set_seed", (DL_FUNC) &_KODAMA_set_seed, 1},
    {"_KODAMA_floyd", (DL_FUNC) &_KODAMA_floyd, 1},
    {"_KODAMA_transformy", (DL_FUNC) &_KODAMA_transformy, 1},
    {"_KODAMA_PLSDACV_simpls", (DL_FUNC) &_KODAMA_PLSDACV_simpls, 4},
    {"_KODAMA_PLSDACV_fastpls", (DL_FUNC) &_KODAMA_PLSDACV_fastpls, 4},
    {"_KODAMA_corecpp", (DL_FUNC) &_KODAMA_corecpp, 10},
    {"KODAMA_irlba_pca_dense", (DL_FUNC) &KODAMA_irlba_pca_dense, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_KODAMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
