# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call(`_KODAMA_set_seed`, seed))
}

floyd <- function(data) {
    .Call(`_KODAMA_floyd`, data)
}

transformy <- function(y) {
    .Call(`_KODAMA_transformy`, y)
}

PLSDACV_simpls <- function(x, cl, constrain, k) {
    .Call(`_KODAMA_PLSDACV_simpls`, x, cl, constrain, k)
}

PLSDACV_fastpls <- function(x, cl, constrain, k) {
    .Call(`_KODAMA_PLSDACV_fastpls`, x, cl, constrain, k)
}

corecpp <- function(x, xTdata, clbest, Tcycle, FUN, fparpls, Xconstrain, fix, shake, proj) {
    .Call(`_KODAMA_corecpp`, x, xTdata, clbest, Tcycle, FUN, fparpls, Xconstrain, fix, shake, proj)
}

